// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package lark_test contains tests for the Lark grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by make.go
//
package lark_test

import (
	"bramp.net/antlr4/internal"
	"bramp.net/antlr4/lark"

	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
	"grammars-v4/lark/examples/ab.lark",
	"grammars-v4/lark/examples/common.lark",
	"grammars-v4/lark/examples/json.lark",
	"grammars-v4/lark/examples/lark.lark",
	"grammars-v4/lark/examples/leading_underscore_grammar.lark",
	"grammars-v4/lark/examples/multiple2.lark",
	"grammars-v4/lark/examples/multiple3.lark",
	"grammars-v4/lark/examples/multiples.lark",
	"grammars-v4/lark/examples/negative_priority.lark",
	"grammars-v4/lark/examples/no_newline_at_end.lark",
	"grammars-v4/lark/examples/python.lark",
	"grammars-v4/lark/examples/python2.lark",
	"grammars-v4/lark/examples/python3.lark",
	"grammars-v4/lark/examples/template_lark.lark",
	"grammars-v4/lark/examples/templates.lark",
	"grammars-v4/lark/examples/test.lark",
	"grammars-v4/lark/examples/test_relative_import.lark",
	"grammars-v4/lark/examples/test_relative_import_of_nested_grammar.lark",
	"grammars-v4/lark/examples/test_relative_import_of_nested_grammar__grammar_to_import.lark",
	"grammars-v4/lark/examples/test_relative_import_of_nested_grammar__nested_grammar.lark",
	"grammars-v4/lark/examples/test_relative_import_preserves_leading_underscore.lark",
	"grammars-v4/lark/examples/test_relative_import_rename.lark",
	"grammars-v4/lark/examples/test_relative_import_rules_dependencies_imported_only_once.lark",
	"grammars-v4/lark/examples/test_relative_import_unicode.lark",
	"grammars-v4/lark/examples/test_relative_multi_import.lark",
	"grammars-v4/lark/examples/test_relative_rule_import.lark",
	"grammars-v4/lark/examples/test_relative_rule_import_drop_ignore.lark",
	"grammars-v4/lark/examples/test_relative_rule_import_rename.lark",
	"grammars-v4/lark/examples/test_relative_rule_import_subrule.lark",
	"grammars-v4/lark/examples/test_relative_rule_import_subrule_no_conflict.lark",
	"grammars-v4/lark/examples/test_templates_import.lark",
	"grammars-v4/lark/examples/test_unicode.lark",
	"grammars-v4/lark/examples/three_rules_using_same_token.lark",
	"grammars-v4/lark/examples/unicode.lark",
}

type exampleListener struct {
	*lark.BaseLarkParserListener
}

func (l *exampleListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}
func Example() {
	// Setup the input
	is := antlr.NewInputStream("...some text to parse...")

	// Create the Lexer
	lexer := lark.NewLarkLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := lark.NewLarkParser(stream)
	p.BuildParseTrees = true
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))

	// Finally walk the tree
	tree := p.Start()
	antlr.ParseTreeWalkerDefault.Walk(&exampleListener{}, tree)
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("..", filename))
	if err != nil {
		return nil, err
	}

	return input, nil
}

func TestLarkLexer(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := lark.NewLarkLexer(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			tok := lexer.NextToken()
			if tok.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i >= MAX_TOKENS {
			t.Errorf("NewLarkLexer(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func TestLarkParser(t *testing.T) {
	// TODO(bramp): Run this test with and without p.BuildParseTrees

	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := lark.NewLarkLexer(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := lark.NewLarkParser(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(internal.NewTestingErrorListener(t, file))

		// Finally test
		p.Start()

		// TODO(bramp): If there is a "file.tree", then compare the output
		// TODO(bramp): If there is a "file.errors", then check the error
	}
}
