// Package vhdl_test contains tests for the vhdl grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by maketest.go
//
package vhdl_test

import (
	"bramp.net/antlr4-grammars/internal"
	"bramp.net/antlr4-grammars/vhdl"

	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
	"grammars-v4/vhdl/examples/add_pkg.vhd",
	"grammars-v4/vhdl/examples/arith.vhd",
	"grammars-v4/vhdl/examples/misc.vhd",
	"grammars-v4/vhdl/examples/numeric_bit-body.vhd",
	"grammars-v4/vhdl/examples/numeric_bit.vhd",
	"grammars-v4/vhdl/examples/numeric_std-body.vhd",
	"grammars-v4/vhdl/examples/numeric_std.vhd",
	"grammars-v4/vhdl/examples/signed.vhd",
	"grammars-v4/vhdl/examples/standard.vhd",
	"grammars-v4/vhdl/examples/std_logic_1164.vhd",
	"grammars-v4/vhdl/examples/std_logic_1164_body.vhd",
	"grammars-v4/vhdl/examples/std_logic_textio.vhd",
	"grammars-v4/vhdl/examples/textio.vhd",
	"grammars-v4/vhdl/examples/unsigned.vhd",
}

type exampleListener struct {
	*vhdl.BasevhdlListener
}

func (l *exampleListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}

func Example() {
	// Setup the input
	is := antlr.NewInputStream("...some text to parse...")

	// TODO(bramp) Add note about Case Insensitive grammers

	// Create the Lexer
	lexer := vhdl.NewvhdlLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := vhdl.NewvhdlParser(stream)
	p.BuildParseTrees = true
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))

	// Finally walk the tree
	tree := p.Design_file()
	antlr.ParseTreeWalkerDefault.Walk(&exampleListener{}, tree)
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("..", filename))
	if err != nil {
		return nil, err
	}

	return input, nil
}

func TestvhdlLexer(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := vhdl.NewvhdlLexer(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			t := lexer.NextToken()
			if t.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i == MAX_TOKENS {
			t.Errorf("NewvhdlLexer(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func TestvhdlParser(t *testing.T) {
	// TODO(bramp): Run this test with and without p.BuildParseTrees

	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := vhdl.NewvhdlLexer(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := vhdl.NewvhdlParser(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(internal.NewTestingErrorListener(t))

		// Finally test
		p.Design_file()
	}
}
