// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package rpn_test contains tests for the rpn grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by maketest.go
//
package rpn_test

import (
	"bramp.net/antlr4/internal"
	"bramp.net/antlr4/rpn"

	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
	"grammars-v4/rpn/examples/cos.txt",
	"grammars-v4/rpn/examples/number1.txt",
	"grammars-v4/rpn/examples/number2.txt",
	"grammars-v4/rpn/examples/number3.txt",
	"grammars-v4/rpn/examples/number4.txt",
	"grammars-v4/rpn/examples/number5.txt",
	"grammars-v4/rpn/examples/pow1.txt",
	"grammars-v4/rpn/examples/precedence1.txt",
	"grammars-v4/rpn/examples/pythagoras.txt",
	"grammars-v4/rpn/examples/pythagoras2.txt",
	"grammars-v4/rpn/examples/simple.txt",
	"grammars-v4/rpn/examples/variable1.txt",
	"grammars-v4/rpn/examples/variable2.txt",
}

type exampleListener struct {
	*rpn.BaserpnListener
}

func (l *exampleListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}

func Example() {
	// Setup the input
	is := antlr.NewInputStream("...some text to parse...")

	// Create the Lexer
	lexer := rpn.NewrpnLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := rpn.NewrpnParser(stream)
	p.BuildParseTrees = true
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))

	// Finally walk the tree
	tree := p.Expression()
	antlr.ParseTreeWalkerDefault.Walk(&exampleListener{}, tree)
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("../", filename))
	if err != nil {
		return nil, err
	}

	return input, nil
}

func TestRpnLexer(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := rpn.NewrpnLexer(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			t := lexer.NextToken()
			if t.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i >= MAX_TOKENS {
			t.Errorf("NewrpnLexer(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func TestRpnParser(t *testing.T) {
	// TODO(bramp): Run this test with and without p.BuildParseTrees

	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := rpn.NewrpnLexer(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := rpn.NewrpnParser(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(internal.NewTestingErrorListener(t, file))

		// Finally test
		p.Expression()
	}
}
