// Package agc_test contains tests for the agc grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by maketest.go
//
package agc_test

import (
	"bramp.net/antlr4test-go/agc"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
	"grammars-v4/agc/examples/501_RESTART_TABLES_AND_ROUTINES.agc",
	"grammars-v4/agc/examples/ASSEMBLY_AND_OPERATION_INFORMATION.agc",
	"grammars-v4/agc/examples/DOWN-TELEMETRY_PROGRAM.agc",
	"grammars-v4/agc/examples/DUMMY_501_INITIALIZATION.agc",
	"grammars-v4/agc/examples/Default.style",
	"grammars-v4/agc/examples/ERASABLE_ASSIGNMENTS.agc",
	"grammars-v4/agc/examples/FRESH_START_AND_RESTART.agc",
	"grammars-v4/agc/examples/IMU_PERFORMANCE_TESTS_1.agc",
	"grammars-v4/agc/examples/INTERRUPT_TRANSFER_ROUTINES.agc",
	"grammars-v4/agc/examples/KEYRUPT_UPRUPT_FRESH_START.agc",
	"grammars-v4/agc/examples/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc",
	"grammars-v4/agc/examples/SUM-CHECK_END_OF_RECORD_MARKS.agc",
	"grammars-v4/agc/examples/Template.agc",
	"grammars-v4/agc/examples/VERIFICATION_ASSISTANCE_PROGRAMS.agc",
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("..", filename))
	if err != nil {
		return nil, err
	}

	return input, nil
}

// TODO Add an Example func

func TestagcLexer(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := agc.NewagcLexer(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			t := lexer.NextToken()
			if t.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i == MAX_TOKENS {
			t.Errorf("NewagcLexer(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func TestagcParser(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := agc.NewagcLexer(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := agc.NewagcParser(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(antlr.NewDiagnosticErrorListener(true)) // TODO Change this
		p.AddErrorListener(antlr.NewConsoleErrorListener())

		// Finally test
		p.Prog()

		// TODO Check for errors
	}
}
