// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package plsql_test contains tests for the PlSql grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by make.go
//
package plsql_test

import (
	"bramp.net/antlr4/internal"
	"bramp.net/antlr4/plsql"

	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"strings"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
	"grammars-v4/plsql/examples-sql-script/delete_as_regular_id.pkb",
	"grammars-v4/plsql/examples-sql-script/deterministic_function.pks",
	"grammars-v4/plsql/examples-sql-script/e_in_out_parameters.pks",
	"grammars-v4/plsql/examples-sql-script/green_run.sql",
	"grammars-v4/plsql/examples-sql-script/green_table.sql",
	"grammars-v4/plsql/examples-sql-script/green_tools.pkb",
	"grammars-v4/plsql/examples-sql-script/green_tools.pks",
	"grammars-v4/plsql/examples-sql-script/green_tools_review.sql",
	"grammars-v4/plsql/examples-sql-script/in_out_parameters.pks",
	"grammars-v4/plsql/examples-sql-script/key_word_as_param.pkb",
	"grammars-v4/plsql/examples-sql-script/package_with_schema.pkb",
	"grammars-v4/plsql/examples-sql-script/package_with_schema.pks",
	"grammars-v4/plsql/examples-sql-script/pipe_row.pkb",
	"grammars-v4/plsql/examples-sql-script/pragma_exception_init.pks",
	"grammars-v4/plsql/examples-sql-script/proc_over_dblink_as_nvl_param.pkb",
	"grammars-v4/plsql/examples-sql-script/result_cache_function.pks",
	"grammars-v4/plsql/examples-sql-script/show_errors.pks",
	"grammars-v4/plsql/examples-sql-script/substr_as_regular_id.pkb",
	"grammars-v4/plsql/examples-sql-script/type_body_elements.sql",
}

type exampleListener struct {
	*plsql.BasePlSqlParserListener
}

func (l *exampleListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}
func Example() {
	// Setup the input (which this parser expects to be uppercased).
	is := antlr.NewInputStream(strings.ToUpper("...some text to parse..."))

	// Create the Lexer
	lexer := plsql.NewPlSqlLexer(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := plsql.NewPlSqlParser(stream)
	p.BuildParseTrees = true
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))

	// Finally walk the tree
	tree := p.Sql_script()
	antlr.ParseTreeWalkerDefault.Walk(&exampleListener{}, tree)
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("..", filename))
	if err != nil {
		return nil, err
	}

	input = internal.NewCaseChangingStream(input, true)
	return input, nil
}

func TestPlSqlLexer(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := plsql.NewPlSqlLexer(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			t := lexer.NextToken()
			if t.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i >= MAX_TOKENS {
			t.Errorf("NewPlSqlLexer(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func TestPlSqlParser(t *testing.T) {
	// TODO(bramp): Run this test with and without p.BuildParseTrees

	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := plsql.NewPlSqlLexer(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := plsql.NewPlSqlParser(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(internal.NewTestingErrorListener(t, file))

		// Finally test
		p.Sql_script()

		// TODO(bramp): If there is a "file.tree", then compare the output
		// TODO(bramp): If there is a "file.errors", then check the error
	}
}
