// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// maketest creates the test and example files for the given grammar.
package main

import (
	"bramp.net/antlr4/internal"
	"fmt"
	"github.com/iancoleman/strcase"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const COPYRIGHT = `// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

`

const DOCFILE = `{{template "copyright" .}}
package {{ .PackageName }} // import "bramp.net/antlr4/{{ .PackageName }}"

`

// TESTFILE is the template for a go test file for this grammar.
// It expects to be executed with a pom.
const TESTFILE = `{{template "copyright" .}}
// Package {{ .PackageName }}_test contains tests for the {{ .Project.LongName }} grammar.
// The tests should be run with the -timeout flag, to ensure the parser doesn't
// get stuck.
//
// Do not edit this file, it is generated by maketest.go
//
package {{ .PackageName }}_test

import (
	"bramp.net/antlr4/{{ .PackageName }}"
	"bramp.net/antlr4/internal"

	"fmt"
	"github.com/antlr/antlr4/runtime/Go/antlr"
	"path/filepath"
	"testing"
)

const MAX_TOKENS = 1000000

var examples = []string{
{{- range $_, $example := .Project.Examples }}
	{{ printf "%q" . }},
{{- end }}
}

type exampleListener struct {
	*{{ .PackageName }}.Base{{ .Project.ListenerName }}
}

func (l *exampleListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	fmt.Println(ctx.GetText())
}

func Example() {
	{{- if eq .Project.CaseInsensitiveType "UPPER" }}
	// Setup the input (which this parser expects to be uppercased).
	is := antlr.NewInputStream(strings.ToUpper("...some text to parse..."))
	{{ else if eq .Project.CaseInsensitiveType "lower" }}
	// Setup the input (which this parser expects to be lowercased).
	is := antlr.NewInputStream(strings.ToLower("...some text to parse..."))
	{{ else }}
	// Setup the input
	is := antlr.NewInputStream("...some text to parse...")
	{{- end }}

	// Create the Lexer
	lexer := {{ .PackageName }}.New{{ .Project.LexerName }}(is)
	stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := {{ .PackageName }}.New{{ .Project.ParserName }}(stream)
	p.BuildParseTrees = true
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))

	// Finally walk the tree
	tree := p.{{ .Project.EntryPoint | Title }}()
	antlr.ParseTreeWalkerDefault.Walk(&exampleListener{}, tree)
}

func newCharStream(filename string) (antlr.CharStream, error) {
	var input antlr.CharStream
	input, err := antlr.NewFileStream(filepath.Join("{{ .Project.ExampleRoot }}", filename))
	if err != nil {
		return nil, err
	}

	{{ if eq .Project.CaseInsensitiveType "UPPER" }}
	input = internal.NewCaseChangingStream(input, true)
	{{ else if eq .Project.CaseInsensitiveType "lower" }}
	input = internal.NewCaseChangingStream(input, false)
	{{ end -}}

	return input, nil
}

func Test{{ .Project.LexerName | Title }}(t *testing.T) {
	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := {{ .PackageName }}.New{{ .Project.LexerName }}(input)

		// Try and read all tokens
		i := 0
		for ; i < MAX_TOKENS; i++ {
			t := lexer.NextToken()
			if t.GetTokenType() == antlr.TokenEOF {
				break
			}
		}

		// If we read too many tokens, then perhaps there is a problem with the lexer.
		if i >= MAX_TOKENS {
			t.Errorf("New{{ .Project.LexerName }}(%q) read %d tokens without finding EOF", file, i)
		}
	}
}

func Test{{ .Project.ParserName | Title }}(t *testing.T) {
	// TODO(bramp): Run this test with and without p.BuildParseTrees

	for _, file := range examples {
		input, err := newCharStream(file)
		if err != nil {
			t.Errorf("Failed to open example file: %s", err)
		}

		// Create the Lexer
		lexer := {{ .PackageName }}.New{{ .Project.LexerName }}(input)
		stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

		// Create the Parser
		p := {{ .PackageName }}.New{{ .Project.ParserName }}(stream)
		p.BuildParseTrees = true
		p.AddErrorListener(internal.NewTestingErrorListener(t, file))

		// Finally test
		p.{{ .Project.EntryPoint | Title }}()
	}
}
`

type templateData struct {
	PackageName string
	Project     *internal.Project
}

func create(filename string, t *template.Template, data *templateData) error {
	out, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create %q: %s", filename, err)
	}

	if err := t.Execute(out, data); err != nil {
		return fmt.Errorf("failed to generate %q: %s", filename, err)
	}

	if err := exec.Command("go", "fmt", filename).Run(); err != nil {
		return fmt.Errorf("failed to `go fmt %q`: %s", filename, err)
	}

	return nil
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output> <input>\n", filepath.Base(os.Args[0]))
		os.Exit(1)
	}

	output := os.Args[1]
	input := os.Args[2]
	path := filepath.Join(input, "pom.xml")
	project, err := internal.ParsePom(path)
	if err != nil {
		log.Fatalf("Failed to read pom file %q: %s", path, err)
	}

	funcs := template.FuncMap{
		"Join":    strings.Join,
		"ToCamel": strcase.ToCamel, // I'd prefer to use ToCamel, but the go target does't do this yet...
		"Title":   strings.Title,
	}

	tmpl := template.Must(template.New("copyright").Parse(COPYRIGHT))

	docTemplate := template.Must(tmpl.New("doc").Parse(DOCFILE))
	testTemplate := template.Must(tmpl.New("test").Funcs(funcs).Parse(TESTFILE))

	data := &templateData{
		PackageName: output,
		Project:     project,
	}

	docfile := filepath.Join(output, "doc.go")
	if err := create(docfile, docTemplate, data); err != nil {
		log.Fatalf("%s", err)
	}

	testfile := filepath.Join(output, output+"_test.go")
	if err := create(testfile, testTemplate, data); err != nil {
		log.Fatalf("%s", err)
	}
}
